### PR TITLE
fix: EnvVar default type allows str

### LINKED ISSUE #173: BUG Literal is incompatible with "NotSet"
**Describe the bug**

With Vscode's Pylance:

```
Argument of type "Literal['#test-me']" cannot be assigned to parameter "default" of type "NotSet" in function "__init__"
  "Literal['#test-me']" is incompatible with "NotSet" Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```
CleanShot 2022-12-12 at 21 16 53@2x

**To Reproduce**
```python
@app.task(daily.at("8am"))
async def daily_notification(channel=EnvArg("CHANNEL", default="#test-me")) -> None:
```

**Expected behavior**

No type error, ie: the `default` field can take `NotSet | str`.

rocketry 2.5.1

### PR DESCRIPTION
**Pull request by tekumara**
resolves #173

### CODE REVIEW

**Comment by Miksus** [comment]
Indeed, the EnvArg can only have str (or not set) as the default value. Thanks for fixing this!

Been a bit lazy recently and currently got lost with adding API to Rocketry. It will take maybe till Wednesday to check this (afraid to merge as being this tired even though I don't see anything wrong).

**Comment by tekumara** [comment]
No problem!

BTW, what do you think about using an `Optional` type and `None` here instead of `NOTSET`, eg:

```python
  def __init__(self, key:Any, default:Optional[str]=None):
```

It would be more idiomatic.

**Comment by Miksus** [comment]
Sorry, have had a bit of a break (been too busy with hobbies) and I hope I can now return to develop Rocketry more frequently. 

I'll try tomorrow come back to this. Sorry for the wait.

**Comment by Miksus** [comment]
Yep, I agree with those changes and looks good! Thanks for adding the type hints!

**Pull request merged**
