### PR TITLE
Fix task deletion bug #130

### PR DESCRIPTION
**Pull request by rohansh-tty**
Minor change in session module's remove_task() method.

### CODE REVIEW

**Comment by Miksus** [comment]
So the test I promised. Put this to the ``rocketry\test\app\test_app.py``.

```python
def test_delete_task():
    set_logging_defaults()

    app = Rocketry(config={'task_execution': 'main'})

    @app.task()
    def task_1():
        ...
    @app.task(name="task 2")
    def task_2():
        ...

    assert len(app.session.tasks) == 2
    
    app.session.remove_task(task_1)
    assert len(app.session.tasks) == 1

    app.session.remove_task("task 2")
    assert len(app.session.tasks) == 0
```

And actually, I realized this fix is not enough though as if someone passes the task function it will still fail.

But this should fix it:

```python
    def remove_task(self, task: Union['Task', str]):
        from rocketry.core.task import Task
        if not isinstance(task, Task):
            task = self[task]
        self.tasks.remove(task)
```

There is a risk of circular imports so not sure if ``Task`` can be imported where the other imports are.

**Comment by rohansh-tty** [comment]
I added the test case and modified the remove_task() method. Also, I didn't face any issues related to circular imports. Here's a quick snap of [test case results](https://ibb.co/FwgXqyF).

**Comment by Miksus** [comment]
Ye, looks good! Moreover, those warnings are most likely just that you are missing some pytest plugins. The CI will fail if warnings are raised there.

I'll try to merge this today or latest tomorrow. Thanks for seeing the effort to fix this!

**Comment by rohansh-tty** [comment]
Ye, Thanks @Miksus for helping me out. Also, I'll install the missing pytest plugins.

**Pull request merged**
